# Generated by Django 5.0.7 on 2024-08-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='address',
            field=models.CharField(blank='False', max_length=100, null='True', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(blank='False', max_length=100, null='True', verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(blank='False', max_length=100, null='True', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(blank='False', max_length=100, null='True', verbose_name='phone'),
        ),
    ]
