# Generated by Django 5.0.7 on 2024-08-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customers_address_alter_customers_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='False', max_length=100, null='True', verbose_name='name')),
                ('price', models.CharField(blank='False', max_length=100, null='True', verbose_name='price')),
            ],
        ),
    ]
