# Generated by Django 5.0.7 on 2024-08-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_products_picture_alter_customers_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank='False', null='True', upload_to='images/', verbose_name='productimage'),
        ),
    ]
