# Generated by Django 5.0.7 on 2024-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_products_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank='False', max_length=100, null='True', verbose_name='Email')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank='False', max_length=100, null='True', verbose_name='Email')),
                ('Password', models.CharField(max_length=100, verbose_name='Password')),
                ('ConfPassword', models.CharField(max_length=100, verbose_name='Confirm Password')),
            ],
        ),
    ]
